public errordomain Starfish.Core.CertError {
    INVALID_HOST_ERROR,
    PARSING_ERROR,
    PRINTING_ERROR,
    FINGERPRINTING_ERROR,
    EXPIRED_ERROR,
    MISMATCH_ERROR,
    CLIENT_CERT_GENERATION_ERROR
}

